// src/lib/modes/imposter/HostControls.svelte
<script lang="ts">
	import { supabase } from '$lib/supabase';
	import HomeButton from '$lib/HomeButton.svelte';
	import { onMount, onDestroy, untrack } from 'svelte';
	import QRCode from 'qrcode';
	import type { Session } from '$lib/modes/index';
	import type { RealtimeChannel } from '@supabase/supabase-js';

	let { session }: { session: Session } = $props();

	type Participant = { id: string; name: string; joined_at: string };
	type Playlist = { id: string; name: string };
	type RoundRow = {
		id: string;
		round: number;
		town_playlist_id: string | null;
		imposter_playlist_id: string | null;
		imposter_participant_id: string | null;
		town_track_id: string | null;
		imposter_track_id: string | null;
	};

	const _initialState = untrack(() => session.playback_state);
	type Phase = 'lobby' | 'setup' | 'playing' | 'revealed' | 'ended';
	let localPhase = $state<Phase>(
		_initialState === 'playing'
			? 'playing'
			: _initialState === 'revealed'
				? 'revealed'
				: _initialState === 'ended'
					? 'ended'
					: 'lobby'
	);

	let qrDataUrl = $state('');
	let participants = $state<Participant[]>([]);
	let playlists = $state<Playlist[]>([]);

	// Setup state
	let townPlaylistId = $state<string | null>(null);
	let imposterPlaylistId = $state<string | null>(null);
	let assignmentMode = $state<'auto' | 'manual' | null>(null);
	let selectedImposterId = $state<string | null>(null); // manual pick

	// Live round state
	let currentRound = $state<RoundRow | null>(null);
	let currentRoundNumber = $state(0);
	let imposterParticipantId = $state<string | null>(null);

	let starting = $state(false);
	let playbackState = $state(untrack(() => session.playback_state));

	let channel: RealtimeChannel | null = null;

	const joinUrl = $derived(
		`${typeof window !== 'undefined' ? window.location.origin : ''}/join/${session.code}`
	);

	function shuffle<T>(arr: T[]): T[] {
		return [...arr].sort(() => Math.random() - 0.5);
	}

	onMount(async () => {
		const url = `${window.location.origin}/join/${session.code}`;
		qrDataUrl = await QRCode.toDataURL(url, {
			margin: 2,
			scale: 6,
			color: { dark: '#ffffff', light: '#18181b' }
		});

		const [{ data: pData }, { data: plData }] = await Promise.all([
			supabase
				.from('participants')
				.select('id, name, joined_at')
				.eq('session_id', session.id)
				.order('joined_at'),
			supabase.from('playlists').select('id, name').order('display_order')
		]);
		participants = pData ?? [];
		playlists = plData ?? [];

		if (localPhase === 'playing' || localPhase === 'revealed' || _initialState === 'paused') {
			await loadLatestRound();
		}

		channel = supabase
			.channel(`imposter-host:${session.id}`)
			.on(
				'postgres_changes',
				{
					event: 'INSERT',
					schema: 'public',
					table: 'participants',
					filter: `session_id=eq.${session.id}`
				},
				(payload) => {
					participants = [...participants, payload.new as Participant];
				}
			)
			.on(
				'postgres_changes',
				{ event: 'UPDATE', schema: 'public', table: 'sessions', filter: `id=eq.${session.id}` },
				(payload) => {
					playbackState = payload.new.playback_state;
					if (payload.new.playback_state === 'ended') localPhase = 'ended';
				}
			)
			.subscribe();
	});

	onDestroy(() => {
		if (channel) supabase.removeChannel(channel);
	});

	async function loadLatestRound() {
		const { data } = await supabase
			.from('imposter_rounds')
			.select(
				'id, round, town_playlist_id, imposter_playlist_id, imposter_participant_id, town_track_id, imposter_track_id'
			)
			.eq('session_id', session.id)
			.order('round', { ascending: false })
			.limit(1)
			.maybeSingle();

		if (data) {
			currentRound = data;
			currentRoundNumber = data.round;
			imposterParticipantId = data.imposter_participant_id;
			townPlaylistId = data.town_playlist_id;
			imposterPlaylistId = data.imposter_playlist_id;
			// Paused mid-round on reload — restore the playing phase
			if (localPhase === 'lobby') localPhase = 'playing';
		}
	}

	function goToSetup(mode: 'auto' | 'manual') {
		assignmentMode = mode;
		selectedImposterId = null;
		localPhase = 'setup';
	}

	async function startRound() {
		if (!townPlaylistId || !imposterPlaylistId) return;
		if (assignmentMode === 'manual' && !selectedImposterId) return;

		starting = true;

		// Pick random imposter if auto
		const imposterId =
			assignmentMode === 'auto'
				? shuffle(participants)[0].id
				: selectedImposterId!;

		// Pick random town track and imposter track
		const [{ data: townTracks }, { data: imposterTracks }] = await Promise.all([
			supabase.from('tracks').select('id').eq('playlist_id', townPlaylistId),
			supabase.from('tracks').select('id').eq('playlist_id', imposterPlaylistId)
		]);

		const townTrack = shuffle(townTracks ?? [])[0];
		const imposterTrack = shuffle(imposterTracks ?? [])[0];

		const nextRound = currentRoundNumber + 1;

		const { data: inserted } = await supabase
			.from('imposter_rounds')
			.insert({
				session_id: session.id,
				round: nextRound,
				town_playlist_id: townPlaylistId,
				imposter_playlist_id: imposterPlaylistId,
				imposter_participant_id: imposterId,
				town_track_id: townTrack?.id ?? null,
				imposter_track_id: imposterTrack?.id ?? null
			})
			.select()
			.single();

		await supabase.from('sessions').update({ playback_state: 'paused' }).eq('id', session.id);

		currentRound = inserted ?? null;
		currentRoundNumber = nextRound;
		imposterParticipantId = imposterId;
		playbackState = 'paused';
		localPhase = 'playing';
		starting = false;
	}

	async function togglePlayback() {
		const next = playbackState === 'playing' ? 'paused' : 'playing';
		await supabase.from('sessions').update({ playback_state: next }).eq('id', session.id);
		playbackState = next;
	}

	async function reveal() {
		await supabase.from('sessions').update({ playback_state: 'revealed' }).eq('id', session.id);
		playbackState = 'revealed';
		localPhase = 'revealed';
	}

	async function endSession() {
		await supabase.from('sessions').update({ playback_state: 'ended' }).eq('id', session.id);
		playbackState = 'ended';
		localPhase = 'ended';
	}

	const imposterName = $derived(
		participants.find((p) => p.id === imposterParticipantId)?.name ?? null
	);
</script>

{#if localPhase === 'lobby'}
	<div
		class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col items-center gap-6 px-5 py-6"
	>
		<div class="flex w-full items-center justify-between gap-4">
			<p class="music-kicker">Imposter Host</p>
			<HomeButton class="shrink-0" />
		</div>

		<section class="music-panel-strong w-full rounded-2xl p-6 text-center">
			<p class="music-kicker mb-3">Room Code</p>
			<p class="stage-title text-7xl font-black tracking-widest sm:text-8xl">{session.code}</p>
			<p class="mt-4 text-sm font-semibold text-cyan-100">Get everyone into the room first</p>
		</section>

		{#if qrDataUrl}
			<div class="music-panel rounded-2xl p-4">
				<img src={qrDataUrl} alt="QR code to join session" class="h-52 w-52" />
			</div>
		{/if}

		<p class="max-w-sm text-center text-xs break-all text-zinc-400">{joinUrl}</p>

		<div class="music-panel w-full rounded-2xl p-5">
			<p class="music-kicker mb-3">Participants ({participants.length})</p>
			{#if participants.length === 0}
				<p class="text-sm text-zinc-400">No one has joined yet.</p>
			{:else}
				<ul class="flex flex-col gap-2">
					{#each participants as p (p.id)}
						<li class="rounded-xl bg-white/5 px-5 py-4 font-semibold">{p.name}</li>
					{/each}
				</ul>
			{/if}
		</div>

		{#if participants.length >= 2}
			<div class="flex w-full max-w-sm flex-col gap-3">
				<button
					onclick={() => goToSetup('auto')}
					class="primary-glow rounded-2xl py-5 text-xl font-black text-white transition active:scale-95"
				>
					Auto-pick Imposter
				</button>
				<button
					onclick={() => goToSetup('manual')}
					class="music-panel rounded-2xl py-5 text-xl font-black text-white transition hover:border-white/25 active:scale-95"
				>
					Pick Imposter Manually
				</button>
			</div>
		{:else}
			<p class="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-300">
				Waiting for at least 2 participants...
			</p>
		{/if}
	</div>

{:else if localPhase === 'setup'}
	<div
		class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col gap-6 px-5 py-6"
	>
		<div class="flex items-start justify-between gap-4">
			<div>
				<p class="music-kicker">Imposter Host</p>
				<h2 class="stage-title mt-2 text-4xl font-black">Set up the round</h2>
			</div>
			<HomeButton class="shrink-0" />
		</div>

		<!-- Town playlist -->
		<div class="music-panel rounded-2xl p-5">
			<p class="music-kicker mb-3">Town playlist</p>
			<p class="mb-3 text-sm text-zinc-400">Everyone except the imposter hears a track from this.</p>
			<div class="flex flex-wrap gap-2">
				{#each playlists as pl (pl.id)}
					<button
						onclick={() => (townPlaylistId = pl.id)}
						class="rounded-xl px-4 py-2 text-sm font-semibold transition-all {townPlaylistId === pl.id
							? 'bg-cyan-600 text-white'
							: 'bg-zinc-800 text-white hover:bg-zinc-700'}"
					>
						{pl.name}
					</button>
				{/each}
			</div>
		</div>

		<!-- Imposter playlist -->
		<div class="music-panel rounded-2xl p-5">
			<p class="music-kicker mb-3">Imposter playlist</p>
			<p class="mb-3 text-sm text-zinc-400">The imposter hears a random track from this instead.</p>
			<div class="flex flex-wrap gap-2">
				{#each playlists as pl (pl.id)}
					<button
						onclick={() => (imposterPlaylistId = pl.id)}
						class="rounded-xl px-4 py-2 text-sm font-semibold transition-all {imposterPlaylistId ===
						pl.id
							? 'bg-red-600 text-white'
							: 'bg-zinc-800 text-white hover:bg-zinc-700'}"
					>
						{pl.name}
					</button>
				{/each}
			</div>
		</div>

		<!-- Manual imposter pick -->
		{#if assignmentMode === 'manual'}
			<div class="music-panel rounded-2xl p-5">
				<p class="music-kicker mb-3">Pick the imposter</p>
				<div class="flex flex-wrap gap-2">
					{#each participants as p (p.id)}
						<button
							onclick={() => (selectedImposterId = p.id)}
							class="rounded-xl px-4 py-3 font-semibold transition-all active:scale-95 {selectedImposterId ===
							p.id
								? 'bg-red-600 text-white'
								: 'bg-zinc-800 text-white hover:bg-zinc-700'}"
						>
							{p.name}
						</button>
					{/each}
				</div>
			</div>
		{:else}
			<div class="music-panel rounded-2xl p-5">
				<p class="music-kicker mb-1">Imposter selection</p>
				<p class="text-sm text-zinc-400">A random participant will be chosen when you start.</p>
			</div>
		{/if}

		<div class="mt-auto flex gap-3">
			<button
				onclick={() => (localPhase = 'lobby')}
				class="music-panel flex-1 rounded-2xl py-4 font-bold transition hover:border-white/25"
			>
				Back
			</button>
			<button
				onclick={startRound}
				disabled={starting ||
					!townPlaylistId ||
					!imposterPlaylistId ||
					(assignmentMode === 'manual' && !selectedImposterId)}
				class="flex-1 rounded-2xl bg-emerald-600 py-4 text-lg font-black text-white transition-colors hover:bg-emerald-500 disabled:opacity-30"
			>
				{starting ? 'Starting...' : 'Start Round'}
			</button>
		</div>
	</div>

{:else if localPhase === 'playing'}
	<div
		class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col gap-6 px-5 py-6"
	>
		<div class="flex w-full items-center justify-between gap-4">
			<div>
				<p class="music-kicker">Imposter Host</p>
				<p class="text-xs text-zinc-500">Round {currentRoundNumber}</p>
			</div>
			<HomeButton class="shrink-0" />
		</div>

		<!-- Play/pause -->
		<div class="flex flex-col items-center gap-4">
			<button
				onclick={togglePlayback}
				class="grid h-40 w-40 place-items-center rounded-full text-2xl font-black text-white shadow-2xl transition-all active:scale-95 {playbackState ===
				'playing'
					? 'bg-red-500 shadow-red-950 hover:bg-red-400'
					: 'bg-emerald-500 shadow-emerald-950 hover:bg-emerald-400'}"
			>
				{playbackState === 'playing' ? 'Pause' : 'Play'}
			</button>
		</div>

		<!-- Participant list with imposter label -->
		<div class="music-panel w-full rounded-2xl p-5">
			<p class="music-kicker mb-3">Participants ({participants.length})</p>
			{#if participants.length === 0}
				<p class="text-sm text-zinc-400">No participants.</p>
			{:else}
				<ul class="flex flex-col gap-2">
					{#each participants as p (p.id)}
						<li class="flex items-center justify-between rounded-xl bg-white/5 px-5 py-4">
							<span class="font-semibold">{p.name}</span>
							{#if p.id === imposterParticipantId}
								<span
									class="rounded-full bg-red-900/60 px-3 py-1 text-xs font-bold text-red-300"
								>
									Imposter
								</span>
							{:else}
								<span
									class="rounded-full bg-zinc-800 px-3 py-1 text-xs font-semibold text-zinc-400"
								>
									Townsperson
								</span>
							{/if}
						</li>
					{/each}
				</ul>
			{/if}
		</div>

		<div class="flex flex-col gap-3">
			<button
				onclick={reveal}
				class="w-full rounded-2xl bg-violet-600 py-5 text-xl font-black text-white transition-colors hover:bg-violet-500 active:scale-95"
			>
				Reveal Imposter
			</button>
			<button
				onclick={endSession}
				class="text-sm text-zinc-600 underline underline-offset-4 hover:text-zinc-400"
			>
				End session
			</button>
		</div>
	</div>

{:else if localPhase === 'revealed'}
	<div
		class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col gap-6 px-5 py-6"
	>
		<div class="flex w-full items-center justify-between gap-4">
			<p class="music-kicker">Imposter Host — Revealed</p>
			<HomeButton class="shrink-0" />
		</div>

		<div class="music-panel-strong rounded-2xl p-8 text-center">
			<p class="music-kicker mb-4">The imposter was...</p>
			<p class="stage-title text-5xl font-black text-red-400">{imposterName ?? '...'}</p>
		</div>

		<!-- Participant list with labels still visible -->
		<div class="music-panel w-full rounded-2xl p-5">
			<p class="music-kicker mb-3">Participants</p>
			<ul class="flex flex-col gap-2">
				{#each participants as p (p.id)}
					<li class="flex items-center justify-between rounded-xl bg-white/5 px-5 py-4">
						<span class="font-semibold">{p.name}</span>
						{#if p.id === imposterParticipantId}
							<span class="rounded-full bg-red-900/60 px-3 py-1 text-xs font-bold text-red-300">
								Imposter
							</span>
						{:else}
							<span class="rounded-full bg-zinc-800 px-3 py-1 text-xs font-semibold text-zinc-400">
								Townsperson
							</span>
						{/if}
					</li>
				{/each}
			</ul>
		</div>

		<!-- New round options -->
		<div class="music-panel rounded-2xl p-5">
			<p class="music-kicker mb-3">Play again?</p>
			<p class="mb-4 text-sm text-zinc-400">
				Same participants, same playlists — pick a new imposter.
			</p>
			<div class="flex flex-col gap-3">
				<button
					onclick={() => goToSetup('auto')}
					class="primary-glow rounded-2xl py-4 text-lg font-black text-white transition active:scale-95"
				>
					Auto-pick new imposter
				</button>
				<button
					onclick={() => goToSetup('manual')}
					class="music-panel rounded-2xl py-4 text-lg font-black text-white transition hover:border-white/25 active:scale-95"
				>
					Pick imposter manually
				</button>
			</div>
		</div>

		<button
			onclick={endSession}
			class="text-sm text-zinc-600 underline underline-offset-4 hover:text-zinc-400"
		>
			End session
		</button>
	</div>

{:else}
	<div
		class="stage-shell flex min-h-screen flex-col items-center justify-center gap-4 p-8 text-center"
	>
		<p class="music-kicker">Imposter Host</p>
		<p class="stage-title text-4xl font-black">Session complete</p>
		<p class="text-zinc-500">Thanks for playing!</p>
		<HomeButton />
	</div>
{/if}

// lib/modes/freeze-dance/HostControls.tsx
import { useState, useEffect, useMemo } from 'react';
import { View, Text, Pressable, ScrollView } from 'react-native';
import { supabase } from '@/lib/supabase';
import { useRealtimeTable } from '@/hooks/useRealtimeTable';
import { HomeButton } from '@/components/HomeButton';
import { QRCodeDisplay } from '@/components/QRCodeDisplay';
import type { ModeProps } from '@/lib/modes';
import type { Participant, Playlist } from '@/lib/types';

type Phase = 'lobby' | 'setup' | 'playing' | 'ended';

function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5);
}

export default function FreezeDanceHostControls({ session }: ModeProps) {
  const initialPhase: Phase = session.playback_state === 'ended' ? 'ended' : 'lobby';
  const [localPhase, setLocalPhase] = useState<Phase>(initialPhase);
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [eliminatedIds, setEliminatedIds] = useState<Set<string>>(new Set());
  const [selectedPlaylistId, setSelectedPlaylistId] = useState<string | null>(null);
  const [currentRound, setCurrentRound] = useState(0);
  const [currentTrackTitle, setCurrentTrackTitle] = useState<string | null>(null);
  const [playbackState, setPlaybackState] = useState(session.playback_state);
  const [starting, setStarting] = useState(false);

  const joinUrl = typeof window !== 'undefined' ? `${window.location.origin}/join/${session.code}` : '';

  const activeParticipants = useMemo(
    () => participants.filter((p) => !eliminatedIds.has(p.id)),
    [participants, eliminatedIds]
  );
  const eliminatedParticipants = useMemo(
    () => participants.filter((p) => eliminatedIds.has(p.id)),
    [participants, eliminatedIds]
  );

  useEffect(() => {
    Promise.all([
      supabase.from('participants').select('id, name, joined_at').eq('session_id', session.id).order('joined_at'),
      supabase.from('playlists').select('id, name').order('display_order'),
    ]).then(([{ data: pData }, { data: plData }]) => {
      setParticipants(pData ?? []);
      setPlaylists(plData ?? []);
    });

    loadCurrentRoundState();
  }, [session.id]);

  useRealtimeTable(`freeze-host:${session.id}`, [
    {
      event: 'INSERT', table: 'participants', filter: `session_id=eq.${session.id}`,
      onPayload: (payload) => setParticipants((prev) => [...prev, payload.new as Participant]),
    },
    {
      event: 'UPDATE', table: 'sessions', filter: `id=eq.${session.id}`,
      onPayload: (payload) => {
        setPlaybackState(payload.new.playback_state);
        if (payload.new.playback_state === 'ended') setLocalPhase('ended');
      },
    },
    {
      event: 'INSERT', table: 'freeze_dance_eliminations',
      onPayload: (payload) => {
        if (payload.new.session_id !== session.id) return;
        setEliminatedIds((prev) => new Set([...prev, payload.new.participant_id]));
      },
    },
    {
      event: 'DELETE', table: 'freeze_dance_eliminations',
      onPayload: () => reloadEliminations(),
    },
  ]);

  async function loadCurrentRoundState() {
    const { data: round } = await supabase
      .from('freeze_dance_rounds')
      .select('round, track_id')
      .eq('session_id', session.id)
      .order('round', { ascending: false })
      .limit(1)
      .maybeSingle();
    if (round) {
      setCurrentRound(round.round);
      const { data: track } = await supabase
        .from('tracks')
        .select('title, playlist_id')
        .eq('id', round.track_id)
        .single();
      if (track?.playlist_id) setSelectedPlaylistId(track.playlist_id);
      if (track?.title) setCurrentTrackTitle(track.title);
      setLocalPhase('playing');
    }
    await reloadEliminations();
  }

  async function reloadEliminations() {
    const { data } = await supabase
      .from('freeze_dance_eliminations')
      .select('participant_id')
      .eq('session_id', session.id);
    setEliminatedIds(new Set((data ?? []).map((r) => r.participant_id)));
  }

  async function startRound() {
    if (!selectedPlaylistId) return;
    setStarting(true);

    const { data: trackRows } = await supabase
      .from('tracks')
      .select('id, title')
      .eq('playlist_id', selectedPlaylistId);

    const track = shuffle(trackRows ?? [])[0];
    if (!track) { setStarting(false); return; }
    setCurrentTrackTitle(track.title);

    const nextRound = currentRound + 1;

    await supabase.from('freeze_dance_eliminations').delete().eq('session_id', session.id);
    await supabase.from('freeze_dance_rounds').insert({
      session_id: session.id,
      round: nextRound,
      track_id: track.id,
    });
    await supabase.from('sessions').update({ playback_state: 'paused' }).eq('id', session.id);

    setEliminatedIds(new Set());
    setCurrentRound(nextRound);
    setPlaybackState('paused');
    setLocalPhase('playing');
    setStarting(false);
  }

  async function togglePlayback() {
    const next = playbackState === 'playing' ? 'paused' : 'playing';
    await supabase.from('sessions').update({ playback_state: next }).eq('id', session.id);
    setPlaybackState(next);
  }

  async function markOut(participantId: string) {
    await supabase.from('freeze_dance_eliminations').insert({
      session_id: session.id,
      participant_id: participantId,
    });
    setEliminatedIds((prev) => new Set([...prev, participantId]));
  }

  async function restoreAll() {
    await supabase.from('freeze_dance_eliminations').delete().eq('session_id', session.id);
    setEliminatedIds(new Set());
  }

  async function endSession() {
    await supabase.from('sessions').update({ playback_state: 'ended' }).eq('id', session.id);
    setPlaybackState('ended');
    setLocalPhase('ended');
  }

  // LOBBY
  if (localPhase === 'lobby') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="items-center gap-6">
        <View className="flex-row w-full items-center justify-between gap-4">
          <Text className="music-kicker">Freeze Dance Host</Text>
          <HomeButton />
        </View>
        <View className="music-panel-strong w-full rounded-2xl p-6 items-center">
          <Text className="music-kicker mb-3">Room Code</Text>
          <Text className="stage-title text-7xl font-black tracking-widest text-white">{session.code}</Text>
          <Text className="mt-4 text-sm font-semibold text-cyan-100">Get everyone into the room first</Text>
        </View>
        {joinUrl ? <QRCodeDisplay url={joinUrl} code={session.code} /> : null}
        <View className="music-panel w-full rounded-2xl p-5">
          <Text className="music-kicker mb-3">Participants ({participants.length})</Text>
          {participants.length === 0 ? (
            <Text className="text-sm text-zinc-400">No one has joined yet.</Text>
          ) : (
            <View className="gap-2">
              {participants.map((p) => (
                <View key={p.id} className="rounded-xl bg-white/5 px-5 py-4">
                  <Text className="font-semibold text-white">{p.name}</Text>
                </View>
              ))}
            </View>
          )}
        </View>
        {participants.length >= 1 ? (
          <Pressable onPress={() => setLocalPhase('setup')} className="primary-glow w-full max-w-sm rounded-2xl py-5 items-center active:scale-95">
            <Text className="text-xl font-black text-white">Pick a playlist & start</Text>
          </Pressable>
        ) : (
          <View className="rounded-full border border-white/10 bg-white/5 px-4 py-2">
            <Text className="text-sm text-zinc-300">Waiting for participants...</Text>
          </View>
        )}
        <Pressable onPress={endSession}>
          <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
        </Pressable>
      </ScrollView>
    );
  }

  // SETUP
  if (localPhase === 'setup') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="gap-6">
        <View className="flex-row items-start justify-between gap-4">
          <View>
            <Text className="music-kicker">Freeze Dance Host</Text>
            <Text className="stage-title mt-2 text-4xl font-black text-white">
              {currentRound > 0 ? `Round ${currentRound + 1}` : 'Pick a playlist'}
            </Text>
          </View>
          <HomeButton />
        </View>
        <View className="music-panel rounded-2xl p-5">
          <Text className="music-kicker mb-3">Playlist</Text>
          <Text className="mb-3 text-sm text-zinc-400">Everyone hears the same random track.</Text>
          <View className="flex-row flex-wrap gap-2">
            {playlists.map((pl) => (
              <Pressable key={pl.id} onPress={() => setSelectedPlaylistId(pl.id)} className={`rounded-xl px-4 py-2 ${selectedPlaylistId === pl.id ? 'bg-cyan-600' : 'bg-zinc-800'}`}>
                <Text className="text-sm font-semibold text-white">{pl.name}</Text>
              </Pressable>
            ))}
          </View>
        </View>
        <View className="flex-row gap-3 mt-auto">
          <Pressable onPress={() => setLocalPhase(currentRound > 0 ? 'playing' : 'lobby')} className="music-panel flex-1 rounded-2xl py-4 items-center">
            <Text className="font-bold text-white">Back</Text>
          </Pressable>
          <Pressable onPress={startRound} disabled={starting || !selectedPlaylistId} className={`flex-1 rounded-2xl bg-emerald-600 py-4 items-center ${starting || !selectedPlaylistId ? 'opacity-30' : ''}`}>
            <Text className="text-lg font-black text-white">
              {starting ? 'Starting...' : currentRound > 0 ? 'Start Next Round' : 'Start Round'}
            </Text>
          </Pressable>
        </View>
        <Pressable onPress={endSession}>
          <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
        </Pressable>
      </ScrollView>
    );
  }

  // PLAYING
  if (localPhase === 'playing') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="gap-5">
        <View className="flex-row w-full items-center justify-between gap-4">
          <View>
            <Text className="music-kicker">Freeze Dance Host</Text>
            <Text className="text-xs text-zinc-500">Round {currentRound}</Text>
          </View>
          <HomeButton />
        </View>

        {activeParticipants.length === 1 ? (
          <View className="music-panel-strong w-full rounded-2xl p-6 items-center">
            <Text className="music-kicker text-yellow-300">Winner!</Text>
            <Text className="stage-title mt-2 text-5xl font-black text-white">{activeParticipants[0].name}</Text>
            <Text className="mt-3 text-zinc-400">Last one standing</Text>
          </View>
        ) : (
          <>
            <View className="items-center gap-4">
              <Pressable onPress={togglePlayback} className={`h-44 w-44 rounded-full items-center justify-center shadow-2xl active:scale-95 ${playbackState === 'playing' ? 'bg-red-500' : 'bg-emerald-500'}`}>
                <Text className="text-3xl font-black text-white">{playbackState === 'playing' ? 'Pause' : 'Play'}</Text>
              </Pressable>
              {playbackState === 'paused' ? (
                <Text className="text-sm font-semibold text-red-400">Music stopped — mark anyone who moved</Text>
              ) : (
                <Text className="text-sm font-semibold text-emerald-400">Music playing</Text>
              )}
              {currentTrackTitle && <Text className="text-sm text-zinc-400">{currentTrackTitle}</Text>}
            </View>

            <View className="music-panel w-full rounded-2xl p-5">
              <View className="flex-row items-center justify-between mb-3">
                <Text className="music-kicker">Still in ({activeParticipants.length})</Text>
                {playbackState === 'paused' && eliminatedIds.size > 0 && (
                  <Pressable onPress={restoreAll}>
                    <Text className="text-xs text-zinc-500 underline underline-offset-4">Restore all</Text>
                  </Pressable>
                )}
              </View>
              <View className="gap-2">
                {activeParticipants.map((p) => (
                  <View key={p.id} className="flex-row items-center justify-between rounded-xl bg-white/5 px-5 py-4">
                    <Text className="font-semibold text-white">{p.name}</Text>
                    {playbackState === 'paused' && (
                      <Pressable onPress={() => markOut(p.id)} className="rounded-full bg-red-900/60 px-3 py-1">
                        <Text className="text-xs font-bold text-red-300">Mark out</Text>
                      </Pressable>
                    )}
                  </View>
                ))}
              </View>
            </View>
          </>
        )}

        {eliminatedParticipants.length > 0 && (
          <View className="music-panel w-full rounded-2xl p-5">
            <Text className="music-kicker mb-3 text-zinc-500">Out ({eliminatedParticipants.length})</Text>
            <View className="gap-2">
              {eliminatedParticipants.map((p) => (
                <View key={p.id} className="flex-row items-center gap-3 rounded-xl bg-white/5 px-5 py-4">
                  <Text className="text-xl">🧊</Text>
                  <Text className="font-semibold text-zinc-400">{p.name}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View className="mt-auto gap-3">
          <Pressable onPress={() => setLocalPhase('setup')} className="w-full rounded-2xl bg-cyan-600 py-4 items-center active:scale-95">
            <Text className="text-lg font-black text-white">Next Round</Text>
          </Pressable>
          <Pressable onPress={endSession}>
            <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
          </Pressable>
        </View>
      </ScrollView>
    );
  }

  // ENDED
  return (
    <View className="stage-shell flex min-h-screen flex-col items-center justify-center gap-4 p-8">
      <Text className="music-kicker">Freeze Dance Host</Text>
      <Text className="stage-title text-4xl font-black text-white">Session complete</Text>
      <Text className="text-zinc-500">Thanks for playing!</Text>
      <HomeButton />
    </View>
  );
}
