// lib/modes/freeze-dance/HostControls.tsx
import { useState, useEffect, useMemo } from 'react';
import { View, Text, Pressable, ScrollView } from 'react-native';
import { supabase } from '@/lib/supabase';
import { useRealtimeTable } from '@/hooks/useRealtimeTable';
import { HomeButton } from '@/components/HomeButton';
import { QRCodeDisplay } from '@/components/QRCodeDisplay';
import type { ModeProps } from '@/lib/modes';
import type { Participant, Playlist } from '@/lib/types';

type Phase = 'lobby' | 'setup' | 'playing' | 'ended';

function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5);
}

export default function FreezeDanceHostControls({ session }: ModeProps) {
  const initialPhase: Phase = session.playback_state === 'ended' ? 'ended' : 'lobby';
  const [localPhase, setLocalPhase] = useState<Phase>(initialPhase);
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [playlists, setPlaylists] = useState<Playlist[]>([]);
  const [eliminatedIds, setEliminatedIds] = useState<Set<string>>(new Set());
  const [selectedPlaylistId, setSelectedPlaylistId] = useState<string | null>(null);
  const [currentRound, setCurrentRound] = useState(0);
  const [currentTrackTitle, setCurrentTrackTitle] = useState<string | null>(null);
  const [playbackState, setPlaybackState] = useState(session.playback_state);
  const [starting, setStarting] = useState(false);

  const joinUrl = typeof window !== 'undefined' ? `${window.location.origin}/join/${session.code}` : '';

  const activeParticipants = useMemo(
    () => participants.filter((p) => !eliminatedIds.has(p.id)),
    [participants, eliminatedIds]
  );
  const eliminatedParticipants = useMemo(
    () => participants.filter((p) => eliminatedIds.has(p.id)),
    [participants, eliminatedIds]
  );

  useEffect(() => {
    Promise.all([
      supabase.from('participants').select('id, name, joined_at').eq('session_id', session.id).order('joined_at'),
      supabase.from('playlists').select('id, name').order('display_order'),
    ]).then(([{ data: pData }, { data: plData }]) => {
      setParticipants(pData ?? []);
      setPlaylists(plData ?? []);
    });

    loadCurrentRoundState();
  }, [session.id]);

  useRealtimeTable(`freeze-host:${session.id}`, [
    {
      event: 'INSERT', table: 'participants', filter: `session_id=eq.${session.id}`,
      onPayload: (payload) => setParticipants((prev) => [...prev, payload.new as Participant]),
    },
    {
      event: 'UPDATE', table: 'sessions', filter: `id=eq.${session.id}`,
      onPayload: (payload) => {
        setPlaybackState(payload.new.playback_state);
        if (payload.new.playback_state === 'ended') setLocalPhase('ended');
      },
    },
    {
      event: 'INSERT', table: 'freeze_dance_eliminations',
      onPayload: (payload) => {
        if (payload.new.session_id !== session.id) return;
        setEliminatedIds((prev) => new Set([...prev, payload.new.participant_id]));
      },
    },
    {
      event: 'DELETE', table: 'freeze_dance_eliminations',
      onPayload: () => reloadEliminations(),
    },
  ]);

  async function loadCurrentRoundState() {
    const { data: round } = await supabase
      .from('freeze_dance_rounds')
      .select('round, track_id')
      .eq('session_id', session.id)
      .order('round', { ascending: false })
      .limit(1)
      .maybeSingle();
    if (round) {
      setCurrentRound(round.round);
      const { data: track } = await supabase
        .from('tracks')
        .select('title, playlist_id')
        .eq('id', round.track_id)
        .single();
      if (track?.playlist_id) setSelectedPlaylistId(track.playlist_id);
      if (track?.title) setCurrentTrackTitle(track.title);
      setLocalPhase('playing');
    }
    await reloadEliminations();
  }

  async function reloadEliminations() {
    const { data } = await supabase
      .from('freeze_dance_eliminations')
      .select('participant_id')
      .eq('session_id', session.id);
    setEliminatedIds(new Set((data ?? []).map((r) => r.participant_id)));
  }

  async function startRound() {
    if (!selectedPlaylistId) return;
    setStarting(true);

    const { data: trackRows } = await supabase
      .from('tracks')
      .select('id, title')
      .eq('playlist_id', selectedPlaylistId);

    const track = shuffle(trackRows ?? [])[0];
    if (!track) { setStarting(false); return; }
    setCurrentTrackTitle(track.title);

    const nextRound = currentRound + 1;

    await supabase.from('freeze_dance_eliminations').delete().eq('session_id', session.id);
    await supabase.from('freeze_dance_rounds').insert({
      session_id: session.id,
      round: nextRound,
      track_id: track.id,
    });
    await supabase.from('sessions').update({ playback_state: 'paused' }).eq('id', session.id);

    setEliminatedIds(new Set());
    setCurrentRound(nextRound);
    setPlaybackState('paused');
    setLocalPhase('playing');
    setStarting(false);
  }

  async function togglePlayback() {
    const next = playbackState === 'playing' ? 'paused' : 'playing';
    await supabase.from('sessions').update({ playback_state: next }).eq('id', session.id);
    setPlaybackState(next);
  }

  async function markOut(participantId: string) {
    await supabase.from('freeze_dance_eliminations').insert({
      session_id: session.id,
      participant_id: participantId,
    });
    setEliminatedIds((prev) => new Set([...prev, participantId]));
  }

  async function restoreAll() {
    await supabase.from('freeze_dance_eliminations').delete().eq('session_id', session.id);
    setEliminatedIds(new Set());
  }

  async function endSession() {
    await supabase.from('sessions').update({ playback_state: 'ended' }).eq('id', session.id);
    setPlaybackState('ended');
    setLocalPhase('ended');
  }

  // LOBBY
  if (localPhase === 'lobby') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="items-center gap-6">
        <View className="flex-row w-full items-center justify-between gap-4">
          <Text className="music-kicker">Freeze Dance Host</Text>
          <HomeButton />
        </View>
        <View className="music-panel-strong w-full rounded-2xl p-6 items-center">
          <Text className="music-kicker mb-3">Room Code</Text>
          <Text className="stage-title text-7xl font-black tracking-widest text-white">{session.code}</Text>
          <Text className="mt-4 text-sm font-semibold text-cyan-100">Get everyone into the room first</Text>
        </View>
        {joinUrl ? <QRCodeDisplay url={joinUrl} code={session.code} /> : null}
        <View className="music-panel w-full rounded-2xl p-5">
          <Text className="music-kicker mb-3">Participants ({participants.length})</Text>
          {participants.length === 0 ? (
            <Text className="text-sm text-zinc-400">No one has joined yet.</Text>
          ) : (
            <View className="gap-2">
              {participants.map((p) => (
                <View key={p.id} className="rounded-xl bg-white/5 px-5 py-4">
                  <Text className="font-semibold text-white">{p.name}</Text>
                </View>
              ))}
            </View>
          )}
        </View>
        {participants.length >= 1 ? (
          <Pressable onPress={() => setLocalPhase('setup')} className="primary-glow w-full max-w-sm rounded-2xl py-5 items-center active:scale-95">
            <Text className="text-xl font-black text-white">Pick a playlist & start</Text>
          </Pressable>
        ) : (
          <View className="rounded-full border border-white/10 bg-white/5 px-4 py-2">
            <Text className="text-sm text-zinc-300">Waiting for participants...</Text>
          </View>
        )}
        <Pressable onPress={endSession}>
          <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
        </Pressable>
      </ScrollView>
    );
  }

  // SETUP
  if (localPhase === 'setup') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="gap-6">
        <View className="flex-row items-start justify-between gap-4">
          <View>
            <Text className="music-kicker">Freeze Dance Host</Text>
            <Text className="stage-title mt-2 text-4xl font-black text-white">
              {currentRound > 0 ? `Round ${currentRound + 1}` : 'Pick a playlist'}
            </Text>
          </View>
          <HomeButton />
        </View>
        <View className="music-panel rounded-2xl p-5">
          <Text className="music-kicker mb-3">Playlist</Text>
          <Text className="mb-3 text-sm text-zinc-400">Everyone hears the same random track.</Text>
          <View className="flex-row flex-wrap gap-2">
            {playlists.map((pl) => (
              <Pressable key={pl.id} onPress={() => setSelectedPlaylistId(pl.id)} className={`rounded-xl px-4 py-2 ${selectedPlaylistId === pl.id ? 'bg-cyan-600' : 'bg-zinc-800'}`}>
                <Text className="text-sm font-semibold text-white">{pl.name}</Text>
              </Pressable>
            ))}
          </View>
        </View>
        <View className="flex-row gap-3 mt-auto">
          <Pressable onPress={() => setLocalPhase(currentRound > 0 ? 'playing' : 'lobby')} className="music-panel flex-1 rounded-2xl py-4 items-center">
            <Text className="font-bold text-white">Back</Text>
          </Pressable>
          <Pressable onPress={startRound} disabled={starting || !selectedPlaylistId} className={`flex-1 rounded-2xl bg-emerald-600 py-4 items-center ${starting || !selectedPlaylistId ? 'opacity-30' : ''}`}>
            <Text className="text-lg font-black text-white">
              {starting ? 'Starting...' : currentRound > 0 ? 'Start Next Round' : 'Start Round'}
            </Text>
          </Pressable>
        </View>
        <Pressable onPress={endSession}>
          <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
        </Pressable>
      </ScrollView>
    );
  }

  // PLAYING
  if (localPhase === 'playing') {
    return (
      <ScrollView className="stage-shell mx-auto min-h-screen w-full max-w-lg px-5 py-6" contentContainerClassName="gap-5">
        <View className="flex-row w-full items-center justify-between gap-4">
          <View>
            <Text className="music-kicker">Freeze Dance Host</Text>
            <Text className="text-xs text-zinc-500">Round {currentRound}</Text>
          </View>
          <HomeButton />
        </View>

        {activeParticipants.length === 1 ? (
          <View className="music-panel-strong w-full rounded-2xl p-6 items-center">
            <Text className="music-kicker text-yellow-300">Winner!</Text>
            <Text className="stage-title mt-2 text-5xl font-black text-white">{activeParticipants[0].name}</Text>
            <Text className="mt-3 text-zinc-400">Last one standing</Text>
          </View>
        ) : (
          <>
            <View className="items-center gap-4">
              <Pressable onPress={togglePlayback} className={`h-44 w-44 rounded-full items-center justify-center shadow-2xl active:scale-95 ${playbackState === 'playing' ? 'bg-red-500' : 'bg-emerald-500'}`}>
                <Text className="text-3xl font-black text-white">{playbackState === 'playing' ? 'Pause' : 'Play'}</Text>
              </Pressable>
              {playbackState === 'paused' ? (
                <Text className="text-sm font-semibold text-red-400">Music stopped — mark anyone who moved</Text>
              ) : (
                <Text className="text-sm font-semibold text-emerald-400">Music playing</Text>
              )}
              {currentTrackTitle && <Text className="text-sm text-zinc-400">{currentTrackTitle}</Text>}
            </View>

            <View className="music-panel w-full rounded-2xl p-5">
              <View className="flex-row items-center justify-between mb-3">
                <Text className="music-kicker">Still in ({activeParticipants.length})</Text>
                {playbackState === 'paused' && eliminatedIds.size > 0 && (
                  <Pressable onPress={restoreAll}>
                    <Text className="text-xs text-zinc-500 underline underline-offset-4">Restore all</Text>
                  </Pressable>
                )}
              </View>
              <View className="gap-2">
                {activeParticipants.map((p) => (
                  <View key={p.id} className="flex-row items-center justify-between rounded-xl bg-white/5 px-5 py-4">
                    <Text className="font-semibold text-white">{p.name}</Text>
                    {playbackState === 'paused' && (
                      <Pressable onPress={() => markOut(p.id)} className="rounded-full bg-red-900/60 px-3 py-1">
                        <Text className="text-xs font-bold text-red-300">Mark out</Text>
                      </Pressable>
                    )}
                  </View>
                ))}
              </View>
            </View>
          </>
        )}

        {eliminatedParticipants.length > 0 && (
          <View className="music-panel w-full rounded-2xl p-5">
            <Text className="music-kicker mb-3 text-zinc-500">Out ({eliminatedParticipants.length})</Text>
            <View className="gap-2">
              {eliminatedParticipants.map((p) => (
                <View key={p.id} className="flex-row items-center gap-3 rounded-xl bg-white/5 px-5 py-4">
                  <Text className="text-xl">🧊</Text>
                  <Text className="font-semibold text-zinc-400">{p.name}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        <View className="mt-auto gap-3">
          <Pressable onPress={() => setLocalPhase('setup')} className="w-full rounded-2xl bg-cyan-600 py-4 items-center active:scale-95">
            <Text className="text-lg font-black text-white">Next Round</Text>
          </Pressable>
          <Pressable onPress={endSession}>
            <Text className="text-sm text-zinc-600 underline underline-offset-4">End session</Text>
          </Pressable>
        </View>
      </ScrollView>
    );
  }

  // ENDED
  return (
    <View className="stage-shell flex min-h-screen flex-col items-center justify-center gap-4 p-8">
      <Text className="music-kicker">Freeze Dance Host</Text>
      <Text className="stage-title text-4xl font-black text-white">Session complete</Text>
      <Text className="text-zinc-500">Thanks for playing!</Text>
      <HomeButton />
    </View>
  );
}

// src/lib/modes/freeze-dance/HostControls.svelte
<script lang="ts">
	import { supabase } from '$lib/supabase';
	import HomeButton from '$lib/HomeButton.svelte';
	import { onMount, onDestroy, untrack } from 'svelte';
	import QRCode from 'qrcode';
	import type { Session } from '$lib/modes/index';
	import type { RealtimeChannel } from '@supabase/supabase-js';

	let { session }: { session: Session } = $props();

	type Participant = { id: string; name: string; joined_at: string };
	type Playlist = { id: string; name: string };

	const _initialState = untrack(() => session.playback_state);
	type Phase = 'lobby' | 'setup' | 'playing' | 'ended';
	let localPhase = $state<Phase>(
		_initialState === 'playing' || _initialState === 'paused'
			? 'playing'
			: _initialState === 'ended'
				? 'ended'
				: 'lobby'
	);

	let qrDataUrl = $state('');
	let participants = $state<Participant[]>([]);
	let playlists = $state<Playlist[]>([]);
	let eliminatedIds = $state<Set<string>>(new Set());

	let selectedPlaylistId = $state<string | null>(null);
	let currentRound = $state(0);
	let playbackState = $state(untrack(() => session.playback_state));
	let starting = $state(false);

	let channel: RealtimeChannel | null = null;

	const joinUrl = $derived(
		`${typeof window !== 'undefined' ? window.location.origin : ''}/join/${session.code}`
	);

	function shuffle<T>(arr: T[]): T[] {
		return [...arr].sort(() => Math.random() - 0.5);
	}

	onMount(async () => {
		const url = `${window.location.origin}/join/${session.code}`;
		qrDataUrl = await QRCode.toDataURL(url, {
			margin: 2,
			scale: 6,
			color: { dark: '#ffffff', light: '#18181b' }
		});

		const [{ data: pData }, { data: plData }] = await Promise.all([
			supabase
				.from('participants')
				.select('id, name, joined_at')
				.eq('session_id', session.id)
				.order('joined_at'),
			supabase.from('playlists').select('id, name').order('display_order')
		]);
		participants = pData ?? [];
		playlists = plData ?? [];

		if (localPhase === 'playing') {
			await loadCurrentRoundState();
		}

		channel = supabase
			.channel(`freeze-host:${session.id}`)
			.on(
				'postgres_changes',
				{
					event: 'INSERT',
					schema: 'public',
					table: 'participants',
					filter: `session_id=eq.${session.id}`
				},
				(payload) => {
					participants = [...participants, payload.new as Participant];
				}
			)
			.on(
				'postgres_changes',
				{ event: 'UPDATE', schema: 'public', table: 'sessions', filter: `id=eq.${session.id}` },
				(payload) => {
					playbackState = payload.new.playback_state;
					if (payload.new.playback_state === 'ended') localPhase = 'ended';
				}
			)
			.on(
				'postgres_changes',
				{
					event: 'INSERT',
					schema: 'public',
					table: 'freeze_dance_eliminations'
				},
				(payload) => {
					if (payload.new.session_id !== session.id) return;
					eliminatedIds = new Set([...eliminatedIds, payload.new.participant_id]);
				}
			)
			.on(
				'postgres_changes',
				{
					event: 'DELETE',
					schema: 'public',
					table: 'freeze_dance_eliminations'
				},
				async () => {
					await reloadEliminations();
				}
			)
			.subscribe();
	});

	onDestroy(() => {
		if (channel) supabase.removeChannel(channel);
	});

	async function loadCurrentRoundState() {
		const { data: round } = await supabase
			.from('freeze_dance_rounds')
			.select('round')
			.eq('session_id', session.id)
			.order('round', { ascending: false })
			.limit(1)
			.maybeSingle();
		if (round) currentRound = round.round;

		await reloadEliminations();
	}

	async function reloadEliminations() {
		const { data } = await supabase
			.from('freeze_dance_eliminations')
			.select('participant_id')
			.eq('session_id', session.id);
		eliminatedIds = new Set((data ?? []).map((r) => r.participant_id));
	}

	async function startRound() {
		if (!selectedPlaylistId) return;
		starting = true;

		const { data: trackRows } = await supabase
			.from('tracks')
			.select('id')
			.eq('playlist_id', selectedPlaylistId);

		const track = shuffle(trackRows ?? [])[0];
		if (!track) { starting = false; return; }

		const nextRound = currentRound + 1;

		await supabase.from('freeze_dance_rounds').insert({
			session_id: session.id,
			round: nextRound,
			track_id: track.id
		});

		// Delete all eliminations for this session (round reset)
		await supabase
			.from('freeze_dance_eliminations')
			.delete()
			.eq('session_id', session.id);

		eliminatedIds = new Set();
		currentRound = nextRound;
		playbackState = 'paused';
		localPhase = 'playing';
		starting = false;
	}

	async function togglePlayback() {
		const next = playbackState === 'playing' ? 'paused' : 'playing';
		await supabase.from('sessions').update({ playback_state: next }).eq('id', session.id);
		playbackState = next;
	}

	async function markOut(participantId: string) {
		await supabase.from('freeze_dance_eliminations').insert({
			session_id: session.id,
			participant_id: participantId
		});
		eliminatedIds = new Set([...eliminatedIds, participantId]);
	}

	async function restoreAll() {
		await supabase
			.from('freeze_dance_eliminations')
			.delete()
			.eq('session_id', session.id);
		eliminatedIds = new Set();
	}

	async function nextRound() {
		localPhase = 'setup';
	}

	async function endSession() {
		await supabase.from('sessions').update({ playback_state: 'ended' }).eq('id', session.id);
		playbackState = 'ended';
		localPhase = 'ended';
	}

	const activeParticipants = $derived(
		participants.filter((p) => !eliminatedIds.has(p.id))
	);
	const eliminatedParticipants = $derived(
		participants.filter((p) => eliminatedIds.has(p.id))
	);
</script>

{#if localPhase === 'lobby'}
	<div
		class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col items-center gap-6 px-5 py-6"
	>
		<div class="flex w-full items-center justify-between gap-4">
			<p class="music-kicker">Freeze Dance Host</p>
			<HomeButton class="shrink-0" />
		</div>

		<section class="music-panel-strong w-full rounded-2xl p-6 text-center">
			<p class="music-kicker mb-3">Room Code</p>
			<p class="stage-title text-7xl font-black tracking-widest sm:text-8xl">{session.code}</p>
			<p class="mt-4 text-sm font-semibold text-cyan-100">Get everyone into the room first</p>
		</section>

		{#if qrDataUrl}
			<div class="music-panel rounded-2xl p-4">
				<img src={qrDataUrl} alt="QR code to join session" class="h-52 w-52" />
			</div>
		{/if}

		<p class="max-w-sm text-center text-xs break-all text-zinc-400">{joinUrl}</p>

		<div class="music-panel w-full rounded-2xl p-5">
			<p class="music-kicker mb-3">Participants ({participants.length})</p>
			{#if participants.length === 0}
				<p class="text-sm text-zinc-400">No one has joined yet.</p>
			{:else}
				<ul class="flex flex-col gap-2">
					{#each participants as p (p.id)}
						<li class="rounded-xl bg-white/5 px-5 py-4 font-semibold">{p.name}</li>
					{/each}
				</ul>
			{/if}
		</div>

		{#if participants.length >= 1}
			<button
				onclick={() => (localPhase = 'setup')}
				class="primary-glow w-full max-w-sm rounded-2xl py-5 text-xl font-black text-white transition active:scale-95"
			>
				Pick a playlist &amp; start
			</button>
		{:else}
			<p class="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-300">
				Waiting for participants...
			</p>
		{/if}
	</div>

{:else if localPhase === 'setup'}
	<div class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col gap-6 px-5 py-6">
		<div class="flex items-start justify-between gap-4">
			<div>
				<p class="music-kicker">Freeze Dance Host</p>
				{#if currentRound > 0}
					<p class="text-xs text-zinc-500">Starting round {currentRound + 1}</p>
				{:else}
					<h2 class="stage-title mt-2 text-4xl font-black">Pick a playlist</h2>
				{/if}
			</div>
			<HomeButton class="shrink-0" />
		</div>

		<div class="music-panel rounded-2xl p-5">
			<p class="music-kicker mb-3">Playlist</p>
			<p class="mb-3 text-sm text-zinc-400">Everyone hears the same random track.</p>
			<div class="flex flex-wrap gap-2">
				{#each playlists as pl (pl.id)}
					<button
						onclick={() => (selectedPlaylistId = pl.id)}
						class="rounded-xl px-4 py-2 text-sm font-semibold transition-all {selectedPlaylistId ===
						pl.id
							? 'bg-cyan-600 text-white'
							: 'bg-zinc-800 text-white hover:bg-zinc-700'}"
					>
						{pl.name}
					</button>
				{/each}
			</div>
		</div>

		<div class="mt-auto flex gap-3">
			<button
				onclick={() => (localPhase = currentRound > 0 ? 'playing' : 'lobby')}
				class="music-panel flex-1 rounded-2xl py-4 font-bold transition hover:border-white/25"
			>
				Back
			</button>
			<button
				onclick={startRound}
				disabled={starting || !selectedPlaylistId}
				class="flex-1 rounded-2xl bg-emerald-600 py-4 text-lg font-black text-white transition-colors hover:bg-emerald-500 disabled:opacity-30"
			>
				{starting ? 'Starting...' : currentRound > 0 ? 'Start Next Round' : 'Start Round'}
			</button>
		</div>
	</div>

{:else if localPhase === 'playing'}
	<div class="stage-shell mx-auto flex min-h-screen w-full max-w-lg flex-col gap-5 px-5 py-6">
		<div class="flex w-full items-center justify-between gap-4">
			<div>
				<p class="music-kicker">Freeze Dance Host</p>
				<p class="text-xs text-zinc-500">Round {currentRound}</p>
			</div>
			<HomeButton class="shrink-0" />
		</div>

		<!-- Play/Pause -->
		<div class="flex flex-col items-center gap-3">
			<button
				onclick={togglePlayback}
				class="grid h-36 w-36 place-items-center rounded-full text-2xl font-black text-white shadow-2xl transition-all active:scale-95 {playbackState ===
				'playing'
					? 'bg-red-500 shadow-red-950 hover:bg-red-400'
					: 'bg-emerald-500 shadow-emerald-950 hover:bg-emerald-400'}"
			>
				{playbackState === 'playing' ? 'Pause' : 'Play'}
			</button>
			{#if playbackState === 'paused'}
				<p class="text-sm font-semibold text-red-400">Music stopped — mark anyone who moved</p>
			{/if}
		</div>

		<!-- Active participants -->
		<div class="music-panel w-full rounded-2xl p-5">
			<div class="mb-3 flex items-center justify-between">
				<p class="music-kicker">Still in ({activeParticipants.length})</p>
				{#if playbackState === 'paused' && eliminatedIds.size > 0}
					<button
						onclick={restoreAll}
						class="text-xs text-zinc-500 underline underline-offset-4 hover:text-zinc-300"
					>
						Restore all
					</button>
				{/if}
			</div>

			{#if activeParticipants.length === 0}
				<p class="text-sm text-zinc-400">No active players.</p>
			{:else}
				<ul class="flex flex-col gap-2">
					{#each activeParticipants as p (p.id)}
						<li class="flex items-center justify-between rounded-xl bg-white/5 px-5 py-4">
							<span class="font-semibold">{p.name}</span>
							{#if playbackState === 'paused'}
								<button
									onclick={() => markOut(p.id)}
									class="rounded-full bg-red-900/60 px-3 py-1 text-xs font-bold text-red-300 transition hover:bg-red-800"
								>
									Mark out
								</button>
							{/if}
						</li>
					{/each}
				</ul>
			{/if}
		</div>

		<!-- Eliminated participants -->
		{#if eliminatedParticipants.length > 0}
			<div class="music-panel w-full rounded-2xl p-5">
				<p class="music-kicker mb-3 text-zinc-500">Out ({eliminatedParticipants.length})</p>
				<ul class="flex flex-col gap-2">
					{#each eliminatedParticipants as p (p.id)}
						<li class="flex items-center gap-3 rounded-xl bg-white/5 px-5 py-4">
							<span class="text-xl" aria-hidden="true">🧊</span>
							<span class="font-semibold text-zinc-400">{p.name}</span>
						</li>
					{/each}
				</ul>
			</div>
		{/if}

		<div class="flex flex-col gap-3">
			<button
				onclick={nextRound}
				class="w-full rounded-2xl bg-cyan-600 py-4 text-lg font-black text-white transition-colors hover:bg-cyan-500 active:scale-95"
			>
				Next Round
			</button>
			<button
				onclick={endSession}
				class="text-sm text-zinc-600 underline underline-offset-4 hover:text-zinc-400"
			>
				End session
			</button>
		</div>
	</div>

{:else}
	<div
		class="stage-shell flex min-h-screen flex-col items-center justify-center gap-4 p-8 text-center"
	>
		<p class="music-kicker">Freeze Dance Host</p>
		<p class="stage-title text-4xl font-black">Session complete</p>
		<p class="text-zinc-500">Thanks for playing!</p>
		<HomeButton />
	</div>
{/if}
